///|
fn main {
  try {
    println(@day01.part1!(0))
    println(@day01.part2!(0))
    println(@day02.part1!(0))
    println(@day02.part2!(0))
    println(@day03.part1!(0))
    println(@day03.part2!(0))
    println(@day04.part1!(0))
    println(@day04.part2!(0))
    println(@day05.part1!(0))
    println(@day05.part2!(0))
    println(@day06.part1!(0))
    println(@day06.part2!(0))
  } catch {
    err => println(err)
  }
}
